to_do_list/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo"))
]

todo/urls.py
from django.urls import path

from todo.views import (
    index,
    TagDeleteView,
    TagUpdateView,
    TaskDeleteView,
    TaskStatusUpdateView,
    TaskUpdateView,
    TagListView,
    TaskCreateView,
    TagCreateView,
)


urlpatterns = [
    path(
        "",
        index,
        name="index"
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "task/<int:pk>/update-status/",
        TaskStatusUpdateView.as_view(),
        name="task-status-update",
    ),
    path(
        "task/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tags/",
        TagListView.as_view(),
        name="tags-list"
    ),
    path(
        "tag/create/",
        TagCreateView.as_view(),
        name="tag-create"
    ),
    path(
        "tag/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tag/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete"
    ),
]


app_name = "todo"

todo/models.py
from django.db import models
from django.urls import reverse


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    def get_absolute_url(self):
        return reverse("todo:task-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.content

    class Meta:
        ordering = ["-is_done", "-created"]

todo/forms.py
from django import forms


from todo.models import Tag, Task


class TaskForm(forms.ModelForm):

    deadline = forms.DateTimeField(
        widget=forms.DateTimeInput(
            attrs={
                "type": "datetime-local"
            }
        ),
        required=True
    )
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = "__all__"

todo/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic

from todo.forms import TaskForm
from todo.models import Tag, Task


def index(request) -> HttpResponse:
    """View function for the home page of the site."""

    tasks_list = Task.objects.all()

    context = {
        "tasks_list": tasks_list
    }

    return render(request, template_name="todo/index.html", context=context)


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = "todo/task_form.html"
    success_url = reverse_lazy("todo:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "todo/task_form.html"
    success_url = reverse_lazy("todo:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "todo/task_confirm_delete_form.html"
    success_url = reverse_lazy("todo:index")


class TaskStatusUpdateView(generic.View):
    model = Task

    def post(self, request, pk) -> HttpResponseRedirect:
        task = get_object_or_404(Task, pk=pk)
        task.is_done = not task.is_done
        task.save()

        return HttpResponseRedirect(reverse("todo:index"))


class TagListView(generic.ListView):
    model = Tag
    template_name = "todo/tag_list.html"
    context_object_name = "tags_list"


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    template_name = "todo/tag_form.html"
    success_url = reverse_lazy("todo:tags-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    template_name = "todo/tag_form.html"
    success_url = reverse_lazy("todo:tags-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    template_name = "todo/tag_confirm_delete_form.html"
    success_url = reverse_lazy("todo:tags-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>Todo list</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous" />
    {% load static %}
    {% comment %} <link rel="stylesheet" href="{% static 'css/styles.css' %}" /> {% endcomment %}
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            {% include 'includes/sidebar.html' %}
          {% endblock %}
        </div>
        <div class="col-sm-10">
          {% block content %}

          {% endblock %}

          {% block pagination %}
            {% comment %} {% include 'includes/pagination.html' %} {% endcomment %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% comment %} {% if user.is_authenticated %}
    <li class="list-group-item">User: {{ user.username }}</li>
    <li class="list-group-item">
      <a href="{% url 'logout' %}">Logout</a>
    </li>
  {% else %}
    <li class="list-group-item">
      <a href="{% url 'login' %}">Login</a>
    </li>
  {% endif %} {% endcomment %}
  <br />
  <li class="list-group-item">
    <a href="{% url 'todo:index' %}">Home</a>
  </li>
  <li class="list-group-item">
    {% comment %} <a href="#">Tag List</a> {% endcomment %}
    <a href="{% url 'todo:tags-list' %}">Tag List</a>
  </li>
  {% comment %} <li class="list-group-item">
    <a href="#">Todo List</a>
    <a href="{% url 'todo_list' %}">Todo List</a>
  </li> {% endcomment %}
</ul>

templates/todo/index.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>ToDo List <a style="float: right;" href="{% url 'todo:task-create' %}">Add Task</a></h1>
    <br>
  {% if tasks_list %}
    {% for task in tasks_list %}
      <ul>
        <li>
          <h3>
            {{ task }}
            {% if task.is_done %}
              <span style="color: green;">Done</span>
            {% else %}
              <span style="color: red;">Not Done</span>
            {% endif %}

            <form method="post" action="{% url 'todo:task-status-update' pk=task.pk %}" style="display: inline;">
                {% csrf_token %}
                <input type="submit" class="btn btn-primary {% if task.is_done %}btn-secondary{% else %}btn-success{% endif %}" value="{% if task.is_done %}Undo{% else %}Complete{% endif %}" style="float: right;" />

              </form>
          </h3>
          <p>Created: {{ task.created }}</p>
          <p>
            Tags:{% for tag in task.tags.all %}
              {{ tag }}
               <a href="{% url 'todo:task-update' task.pk %}">Update</a>
               <a href="{% url 'todo:task-delete' task.pk %}">Delete</a>
            {% endfor %}
          </p>
        </li>
        <hr />
      </ul>
    {% endfor %}
  {% else %}
    <p>There are no Tasks</p>
  {% endif %}
{% endblock %}

templates/todo/tag_confirm_delete_form.html
{% extends 'base.html' %}

{% block content %}
  <p>Are you sure you want to delete the tag: {{ tag }}?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger" />
    <button type="button" class="btn btn-primary" onclick="window.location.href='{% url 'todo:tags-list' %}';">No, return</button>
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:'Update,Create' }} Tag</h1>
  {% if error %}
    <p>{{ error }}</p>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <br />
    <input class="btn btn-primary" type="submit" value="Submit" />
    <input type="hidden" name="next" value="{{ next }}" />
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Tags List <a style="float: right;" href="{% url 'todo:tag-create' %}">+</a></h1>

  {% if tags_list %}
  <table class="table">
    <tr>
      <th>name</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>

    {% for tag in tags_list %}
      <tr>
        <td>{{ tag.name }}</td>
        <td><a href="{% url 'todo:tag-update' tag.pk %}" class="btn btn-primary">Update</a></td>
        <td><a href="{% url 'todo:tag-delete' tag.id %}" class="btn btn-danger">Delete</a></td>

      </tr>
    {% endfor %}
  {% else %}
    <p>There are no Tags</p>
  {% endif %}
{% endblock %}

templates/todo/task_confirm_delete_form.html
{% extends 'base.html' %}

{% block content %}
  <p>Are you sure you want to delete the task: {{ task }}?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger" />
    <button type="button" class="btn btn-primary" onclick="window.location.href='{% url 'todo:index' %}';">No, return</button>
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:'Update,Create' }} Task</h1>
  {% if error %}
    <p>{{ error }}</p>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}

    <br />
    <input class="btn btn-primary" type="submit" value="Submit" />
    <input type="hidden" name="next" value="{{ next }}" />
  </form>
{% endblock %}